import { MigrationInterface, QueryRunner } from "typeorm";

export class FakePosts1622556777491 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
        insert into post (title, body, "creatorId") values ('Strip Nude for Your Killer (Nude per l''assassino)', 'Cross-group optimal utilisation', 1);
insert into post (title, body, "creatorId") values ('Fanboys', 'Configurable well-modulated collaboration', 1);
insert into post (title, body, "creatorId") values ('Magician, The (Ansiktet)', 'Multi-tiered systematic model', 1);
insert into post (title, body, "creatorId") values ('Look Both Ways', 'Reverse-engineered even-keeled hardware', 1);
insert into post (title, body, "creatorId") values ('Big Kahuna, The', 'Virtual impactful groupware', 1);
insert into post (title, body, "creatorId") values ('Sharky''s Machine', 'Extended methodical concept', 1);
insert into post (title, body, "creatorId") values ('Dark Dungeons', 'Multi-tiered content-based encryption', 1);
insert into post (title, body, "creatorId") values ('Annie', 'Ameliorated scalable model', 1);
insert into post (title, body, "creatorId") values ('Close My Eyes', 'Assimilated intangible orchestration', 1);
insert into post (title, body, "creatorId") values ('Real Genius', 'Fully-configurable demand-driven approach', 1);
insert into post (title, body, "creatorId") values ('Blood Games ', 'Ameliorated static framework', 1);
insert into post (title, body, "creatorId") values ('Remote Control', 'Balanced exuding internet solution', 1);
insert into post (title, body, "creatorId") values ('A Fugitive from the Past', 'Managed intangible algorithm', 1);
insert into post (title, body, "creatorId") values ('Monster, The', 'Cross-platform didactic contingency', 1);
insert into post (title, body, "creatorId") values ('There Be Dragons', 'Synergized optimizing interface', 1);
insert into post (title, body, "creatorId") values ('Angry Red Planet, The', 'Monitored stable alliance', 1);
insert into post (title, body, "creatorId") values ('Children of the Corn', 'Persistent multimedia hub', 1);
insert into post (title, body, "creatorId") values ('Swept from the Sea', 'Face to face 4th generation groupware', 1);
insert into post (title, body, "creatorId") values ('Gypsy', 'Fully-configurable context-sensitive hub', 1);
insert into post (title, body, "creatorId") values ('Thomas Crown Affair, The', 'Adaptive reciprocal service-desk', 1);
insert into post (title, body, "creatorId") values ('Protector, The', 'Multi-tiered human-resource implementation', 1);
insert into post (title, body, "creatorId") values ('Bombay Beach', 'Multi-channelled bifurcated attitude', 1);
insert into post (title, body, "creatorId") values ('Luther the Geek', 'Persistent next generation customer loyalty', 1);
insert into post (title, body, "creatorId") values ('Kept Husbands', 'Realigned uniform Graphic Interface', 1);
insert into post (title, body, "creatorId") values ('Ninotchka', 'Digitized next generation customer loyalty', 1);
insert into post (title, body, "creatorId") values ('Vive L''Amour (Ai qing wan sui)', 'Multi-tiered zero defect framework', 1);
insert into post (title, body, "creatorId") values ('Last Days in Vietnam', 'Multi-tiered empowering task-force', 1);
insert into post (title, body, "creatorId") values ('Diary of a Cannibal', 'Optimized logistical task-force', 1);
insert into post (title, body, "creatorId") values ('Dante''s Inferno', 'Devolved foreground strategy', 1);
insert into post (title, body, "creatorId") values ('Hearts and Minds', 'Versatile eco-centric orchestration', 1);
insert into post (title, body, "creatorId") values ('Insidious', 'Front-line multi-state strategy', 1);
insert into post (title, body, "creatorId") values ('Dead Leaves', 'Vision-oriented regional ability', 1);
insert into post (title, body, "creatorId") values ('Wonderland', 'Cross-platform 5th generation migration', 1);
insert into post (title, body, "creatorId") values ('View to a Kill, A', 'Assimilated intermediate customer loyalty', 1);
insert into post (title, body, "creatorId") values ('Primal', 'Open-architected regional definition', 1);
insert into post (title, body, "creatorId") values ('Smooth Talk', 'Re-engineered value-added function', 1);
insert into post (title, body, "creatorId") values ('Cheri', 'Ergonomic impactful matrices', 1);
insert into post (title, body, "creatorId") values ('Vampire Girl vs. Frankenstein Girl (Kyûketsu Shôjo tai Shôjo Furanken)', 'De-engineered needs-based database', 1);
insert into post (title, body, "creatorId") values ('Killing Them Softly', 'Ergonomic well-modulated process improvement', 1);
insert into post (title, body, "creatorId") values ('Thriller: A Cruel Picture (Thriller - en grym film)', 'Horizontal maximized knowledge base', 1);
insert into post (title, body, "creatorId") values ('Joe the King', 'Streamlined explicit artificial intelligence', 1);
insert into post (title, body, "creatorId") values ('Swamp, The (Ciénaga, La)', 'Synergistic didactic flexibility', 1);
insert into post (title, body, "creatorId") values ('Jodhaa Akbar', 'Distributed clear-thinking application', 1);
insert into post (title, body, "creatorId") values ('Dead Calm', 'Reduced value-added analyzer', 1);
insert into post (title, body, "creatorId") values ('Emperor''s New Groove 2: Kronk''s New Groove, The', 'Persevering demand-driven website', 1);
insert into post (title, body, "creatorId") values ('Day for Night (La Nuit Américaine)', 'Multi-channelled hybrid parallelism', 1);
insert into post (title, body, "creatorId") values ('Universal Soldier: Regeneration', 'Reverse-engineered 6th generation Graphical User Interface', 1);
insert into post (title, body, "creatorId") values ('Buddy', 'Synchronised hybrid attitude', 1);
insert into post (title, body, "creatorId") values ('Vigilante', 'Face to face zero administration archive', 1);
insert into post (title, body, "creatorId") values ('Saw II', 'Sharable bottom-line functionalities', 1);
insert into post (title, body, "creatorId") values ('You Light Up My Life', 'Persistent 6th generation hub', 1);
insert into post (title, body, "creatorId") values ('Milarepa', 'Vision-oriented multi-tasking parallelism', 1);
insert into post (title, body, "creatorId") values ('Dare', 'Extended even-keeled functionalities', 1);
insert into post (title, body, "creatorId") values ('Liar, The (Valehtelija)', 'Optimized upward-trending conglomeration', 1);
insert into post (title, body, "creatorId") values ('Two Solutions for One Problem (Dow Rahehal Baraye yek Massaleh)', 'Visionary fault-tolerant open system', 1);
insert into post (title, body, "creatorId") values ('The Concert for Bangladesh', 'Centralized static support', 1);
insert into post (title, body, "creatorId") values ('Heart Is a Lonely Hunter, The', 'Diverse responsive pricing structure', 1);
insert into post (title, body, "creatorId") values ('Pippi on the Run (På rymmen med Pippi Långstrump)', 'Down-sized tangible migration', 1);
insert into post (title, body, "creatorId") values ('8 Heads in a Duffel Bag', 'Compatible web-enabled strategy', 1);
insert into post (title, body, "creatorId") values ('Trumpet of the Swan, The', 'Advanced 24 hour portal', 1);
insert into post (title, body, "creatorId") values ('People, Places, Things', 'Triple-buffered static structure', 1);
insert into post (title, body, "creatorId") values ('Fists in the Pocket (Pugni in tasca, I)', 'Pre-emptive hybrid concept', 1);
insert into post (title, body, "creatorId") values ('Total Eclipse', 'Expanded secondary intranet', 1);
insert into post (title, body, "creatorId") values ('Cloudburst', 'Secured human-resource complexity', 1);
insert into post (title, body, "creatorId") values ('Return to Oz', 'Expanded exuding architecture', 1);
insert into post (title, body, "creatorId") values ('Danny Deckchair', 'Intuitive holistic support', 1);
insert into post (title, body, "creatorId") values ('Escape Plan', 'Expanded web-enabled internet solution', 1);
insert into post (title, body, "creatorId") values ('Beyond the Black Rainbow', 'Digitized exuding installation', 1);
insert into post (title, body, "creatorId") values ('Return of the Living Dead 3', 'Enhanced global middleware', 1);
insert into post (title, body, "creatorId") values ('Desert Fox, The', 'Assimilated logistical access', 1);
insert into post (title, body, "creatorId") values ('Windy Day (Tuulinen päivä)', 'Synergistic static website', 1);
insert into post (title, body, "creatorId") values ('Stand and Deliver', 'Persistent fault-tolerant internet solution', 1);
insert into post (title, body, "creatorId") values ('Bulworth', 'Integrated client-driven challenge', 1);
insert into post (title, body, "creatorId") values ('Bliss', 'Future-proofed actuating time-frame', 1);
insert into post (title, body, "creatorId") values ('Rovaniemen markkinoilla', 'Managed actuating orchestration', 1);
insert into post (title, body, "creatorId") values ('Flight of the Phoenix, The', 'Upgradable object-oriented circuit', 1);
insert into post (title, body, "creatorId") values ('Cut', 'Distributed background ability', 1);
insert into post (title, body, "creatorId") values ('Line, The (La linea)', 'Robust encompassing alliance', 1);
insert into post (title, body, "creatorId") values ('Rocky Horror Picture Show, The', 'Organized 24 hour knowledge base', 1);
insert into post (title, body, "creatorId") values ('Chronicle of a Disappearance', 'Cross-platform hybrid service-desk', 1);
insert into post (title, body, "creatorId") values ('Wreckers', 'Visionary client-driven infrastructure', 1);
insert into post (title, body, "creatorId") values ('Waterworld', 'Universal even-keeled firmware', 1);
insert into post (title, body, "creatorId") values ('Cottage, The', 'Innovative full-range emulation', 1);
insert into post (title, body, "creatorId") values ('Footlight Parade', 'Ameliorated actuating encryption', 1);
insert into post (title, body, "creatorId") values ('Bandit: Bandit''s Silver Angel (Smokey and the Bandit 7) (Bandit: Bandit and the Silver Angel)', 'Stand-alone radical intranet', 1);
insert into post (title, body, "creatorId") values ('Say Anything...', 'Streamlined cohesive productivity', 1);
insert into post (title, body, "creatorId") values ('Women in Love', 'Front-line composite leverage', 1);
insert into post (title, body, "creatorId") values ('Creep Van', 'Multi-lateral client-server Graphical User Interface', 1);
insert into post (title, body, "creatorId") values ('Living Daylights, The', 'Front-line optimizing knowledge user', 1);
insert into post (title, body, "creatorId") values ('Operator 13', 'Self-enabling 24/7 time-frame', 1);
insert into post (title, body, "creatorId") values ('Accused, The', 'User-friendly client-driven system engine', 1);
insert into post (title, body, "creatorId") values ('Hotel', 'Persevering contextually-based budgetary management', 1);
insert into post (title, body, "creatorId") values ('Liquidator, The', 'Total hybrid Graphical User Interface', 1);
insert into post (title, body, "creatorId") values ('Avalon', 'Integrated didactic architecture', 1);
insert into post (title, body, "creatorId") values ('Day the Fish Came Out, The', 'Innovative client-driven protocol', 1);
insert into post (title, body, "creatorId") values ('Twentynine Palms', 'Customer-focused fault-tolerant policy', 1);
insert into post (title, body, "creatorId") values ('Naked Harbour (Vuosaari)', 'Ergonomic reciprocal success', 1);
insert into post (title, body, "creatorId") values ('Flesh and Blood', 'Robust asynchronous methodology', 1);
insert into post (title, body, "creatorId") values ('Dungeon Masters, The', 'User-centric intangible protocol', 1);
insert into post (title, body, "creatorId") values ('Santa Claus Is a Stinker (Le Père Noël est une ordure)', 'Multi-tiered 24/7 website', 1);
`);
  }

  public async down(_: QueryRunner): Promise<void> {}
}
